---
- name: Remove packages
  hosts: all
  become: true

  tasks:
   - name: Removing packages installed by Ansible
     yum:
       name:
         - tree
         - dos2unix
         - vim
         - wget
         - net-tools
         - nmap-ncat
         - zip
         - unzip
         - tmux
         - samba-common-tools
         - realmd
         - oddjob
         - oddjob-mkhomedir
         - sssd
         - adcli
         - krb5-workstation
       state: absent
