---
- name: Install required packages
  hosts: all
  become: true

  tasks:
   - name: Installing tree package
     yum:
       name: tree
       state: latest

   - name: Installing dos2unix package
     yum:
       name: dos2unix 
       state: latest
