---
  - name: Patch Database Servers and Reboot if Needed
    hosts: aws
    become: true

    tasks:
      - name: Check the Uptime of the servers
        shell: "uptime"
        register: Uptime

      - name: Stopping database
        ansible.builtin.service:
          name: mysqld
          state: stopped

      - name: Upgrade all packages but skip the Linux Kernel and Java
        yum:
          name: '*'
          state: latest
          exclude: kernel*,java*,foo*

      - name: Upgrade Java if available but skip the Linux Kernel
        yum:
          name: '*'
          state: latest
          exclude: kernel*
          
      - name: Upgrade Linux Kernel if available
        yum:
          name: '*'
          state: latest

      - name: Check to see if servers need a reboot
        command: needs-restarting -r
        register: result
        ignore_errors: yes

      - name: display result
        debug:
          var: result.rc

      - name: Reboot Server if Necessary
        reboot:
          reboot_timeout: 3600
        when: result.rc == 1

      - name: Verify Database Service started
        ansible.builtin.service:
          name: mysqld
          state: started
